ultraleap/Element

.gitignore, LMNT/cmake/FetchDynASM.cmake, LMNT/include/lmnt/common.h, LMNT/include/lmnt/config.h, LMNT/include/lmnt/interpreter.h, LMNT/include/lmnt/jit.h, LMNT/include/lmnt/jitconfig.h, LMNT/include/lmnt/opcodes.h, LMNT/include/lmnt/ops_misc.h, LMNT/src/lmnt/helpers.h, LMNT/src/lmnt/interpreter.c, LMNT/src/lmnt/jit.c, LMNT/src/lmnt/jit/jit-armv7m.dasc, LMNT/src/lmnt/jit/jit-x86_64.dasc, LMNT/src/lmnt/jit/jithelpers.h, LMNT/src/lmnt/jit/reghelpers-arm-vfp.h, LMNT/src/lmnt/jit/reghelpers-x86.h, LMNT/src/lmnt/opcodes.c, LMNT/src/lmnt/ops_misc.c, LMNT/src/lmnt/ops_trig.c, LMNT/src/lmnt/validation.c, LMNT/test/helpers.h, LMNT/test/test_misc.h
- Reduces the number and complexity of dynamic indexing instructions
- Implements dynamic indexing instructions for JIT (x86_64 and ARMv7-M)
- Adds tests for dynamic indexing instructions
- Fixes several issues in the ARMv7-M JIT (rounding behaviour with NaNs, extern function calls)
- Changed behaviour of `ASSIGNIIx` instruction (now expects the immediate to be a signed int32 not unsigned)
- Fixes runtime checks for stack addresses so it caps at the stack count specified by this function, not the available memory space
- Actually checks that DynASM succeeded in encoding the function before trying to do things with it...
=> LMNT: Indexing updates

LMNT/doc/Instructions.md, LMNT/include/lmnt/opcodes.h, LMNT/include/lmnt/ops_math.h, LMNT/src/jit/jit-armv7m.dasc, LMNT/src/jit/jit-x86_64.dasc, LMNT/src/opcodes.c, LMNT/src/ops_math.c, LMNT/src/validation.c, LMNT/test/test_maths_scalar.h
Adds logarithm instructions to LMNT:
- `LOG`: logarithm using an arbitrary base
- `LN`: natural logarithm (base `e`)
- `LOG2`: log base 2
- `LOG10`: log base 10
JIT implementations just call through to C for now.
=> LMNT: logarithm instructions

LMNT/src/jit/jit-armv7m.dasc, LMNT/src/jit/jit-x86_64.dasc, LMNT/src/jit/jithelpers.h, LMNT/src/jit/reghelpers-arm-vfp.h, LMNT/src/jit/reghelpers-x86.h
Currently, on returning from a function we flush all registers in the cache (to ensure that any cached values are propagated to the function's stack before it returns).
However, this is not necessary: the user does not have access to all values on the stack, only the return values; thus, only these values (and persistent values in the `constants` table) need to be flushed - potentially saving numerous unnecessary instructions on every execution.
=> LMNT JIT: selective flushing of register cache

Element.NET/!1-AST/Declarations/ConstraintDeclaration.cs, Element.NET/!1-AST/Declarations/FunctionDeclaration.cs, Element.NET/!1-AST/Declarations/NamespaceDeclaration.cs, Element.NET/!1-AST/Declarations/StructDeclaration.cs, Element.NET/!2-ValueObjectModel/Intrinsics/Functions/If.cs, Element.NET/!2-ValueObjectModel/Intrinsics/Functions/List.cs, Element.NET/!2-ValueObjectModel/Values/ResolvedBlock.cs, Laboratory/Tests/L0-Parsing/Declarations/Identifiers/IdentifiersStartingWithKeywords-pass.ele, Laboratory/Tests/L0-Parsing/Declarations/Identifiers/IdentifiersStartingWithKeywords/Constraint-pass.ele, Laboratory/Tests/L0-Parsing/Declarations/Identifiers/IdentifiersStartingWithKeywords/Function-pass.ele, Laboratory/Tests/L0-Parsing/Declarations/Identifiers/IdentifiersStartingWithKeywords/Intrinsic-pass.ele, Laboratory/Tests/L0-Parsing/Declarations/Identifiers/IdentifiersStartingWithKeywords/IntrinsicConstraint-pass.ele, Laboratory/Tests/L0-Parsing/Declarations/Identifiers/IdentifiersStartingWithKeywords/IntrinsicFunction-pass.ele, Laboratory/Tests/L0-Parsing/Declarations/Identifiers/IdentifiersStartingWithKeywords/IntrinsicStruct-pass.ele, Laboratory/Tests/L0-Parsing/Declarations/Identifiers/IdentifiersStartingWithKeywords/Struct-pass.ele, Laboratory/Tests/L2-Semantics/_1_UntypedFunctions.cs, Laboratory/Tests/L2-Semantics/_1_UntypedFunctions.ele, Laboratory/Tests/L2-Semantics/_2_TypedFunctions.cs, Laboratory/Tests/L2-Semantics/_2_TypedFunctions.ele, Laboratory/Tests/L2-Semantics/_3_IndexingNamespace.ele, Laboratory/Tests/L2-Semantics/_6_NestedConstructs.cs, Laboratory/Tests/L2-Semantics/_6_NestedConstructs.ele
- Add tests to cover lookup recursing when finding an error when it
shouldnt
- Fix bug where lookup recurses when finding an error instead of
returning the error
- Fix bug where identifiers starting with a keyword would
cause parse error e.g. constraintBlah
- Fix bug where blocks resolved with captures did not include the
captures in their member list (i.e. function calls)
=> Element.NET - SF-473 - Incorrect port constraint identifier cause IdentifierNotFound for declaration

libelement/src/token_internal.cpp
If a space is encountered after a plus, return an
error code instead of failing an assertion.
=> libelement: Return error code in parseerror

libelement/src/interpreter.cpp, libelement/src/object.cpp
could cause a nullptr deref if the user passes a valid pointer to a nullptr
=> libelement: undo setting nullptr to wrapped contents on deletion

Laboratory/Tests/L3-Prelude/For.cs, libelement/src/instruction_tree/evaluator.cpp
The bug was that the outputs from do_evaluate were pointers
to the context which it was using to perform calculations.
=> libelement: Fix bug in for

libelement/src/object_model/intermediaries/list_wrapper.cpp
This proves more useful information about the objects
in the lists, if a type mis-match is found.
=> libelement: Update error msg

libelement/src/instruction_tree/evaluator.cpp, libelement/src/instruction_tree/instructions.hpp, libelement/src/object_model/intrinsics/intrinsic_for.cpp
Fixed a potential bug that andy spotted where we were comparing floats as if they were bool (hoping they had already gone through the bool conversion)
Standardised the use of it everywhere that we were doing bool conversions, which will be helpful later once it's specialised for nans as well
unit tests are unchanged (6 unrelated failing tests)
=> libelement: Fix potential bad bool comparison, and reuse bool conversion everywhere

libelement/src/instruction_tree/instructions.hpp, libelement/src/interpreter.cpp, libelement/src/object_model/declarations/function_declaration.hpp, libelement/src/object_model/declarations/namespace_declaration.cpp, libelement/src/object_model/declarations/struct_declaration.cpp, libelement/src/object_model/error_map.cpp, libelement/src/object_model/expressions/call_expression.cpp, libelement/src/object_model/expressions/indexing_expression.cpp, libelement/src/object_model/expressions/lambda_expression.hpp, libelement/src/object_model/intermediaries/function_instance.cpp, libelement/src/object_model/intermediaries/list_wrapper.cpp, libelement/src/object_model/metainfo.cpp, libelement/src/object_model/object_internal.cpp, libelement/src/object_model/object_model_builder.cpp, libelement/src/object_model/type_annotation.hpp
- Replaces typeof_info with to_string, which will contain more useful information in error messages
- Some cleanup in error messages so that information isn't duplicated, and type names exist for literals
This MR does not make error messages better, just slightly more detailed, such that the error message contains relevant names rather than "ExpressionBodied"
A lot more work is needed to make these error messages nice and consistent
=> libelement: slightly improved error messages

libelement/include/element/interpreter.h, libelement/src/common_internal.cpp, libelement/src/common_internal.hpp, libelement/src/instruction_tree/instructions.hpp, libelement/src/interpreter.cpp
- Adds index for each option in the instruction tree string
- Adds the pointer of the node, so we can tell which are duplicates
- Exposes the function in the public API, so we can access it elsewhere
=> libelement: expose instruction_to_string & changes

LMNT/README.md, LMNT/doc/ExecutionModel.md, LMNT/doc/JIT.md, LMNT/include/lmnt/archive.h, LMNT/include/lmnt/extcalls.h, LMNT/include/lmnt/interpreter.h, LMNT/src/archive.c, LMNT/src/extcalls.c, LMNT/src/interpreter.c, LMNT/src/jit/jit-armv7m.dasc, LMNT/src/jit/jit-x86_64.dasc, LMNT/src/jit/jit.c, LMNT/src/ops_fncall.c, LMNT/test/test_fncall.h, LMNT/test/testhelpers.h, LMNT/test/testsetup_interpreter.h, LMNT/test/testsetup_jit_native.h, LMNT/testapp/main.c
- Renamed lmnt_ictx_* to be lmnt_* since they're the primary API
- Renamed archive-related functions to be lmnt_archive_*
- Changed a few calls to use validated functions since we've already checked it's validated
=> LMNT: rename API functions to be more user-obvious

Laboratory/Tests/L4-Standard-Library/StandardPaths.cs
Circles now go anti-clockwise from "3 o'clock" rather than clockwise from "12 o'clock", and the tests hadn't been updated to reflect this.
=> Laboratory: fixed circle tests in StandardPaths to match updated circle path behaviour

libelement/src/lmnt/compiler.cpp, libelement/src/lmnt/compiler_state.cpp, libelement/src/lmnt/compiler_state.hpp
Fairly naive pass at making conditional execution work properly.
The problem before can be shown by the example:
```
_(a:Num):Num
{
x = a.sub(5)
y = if(true, a, x)
return = y.sub(x)
}
```
When we generate bytecode, previously we have compiled it once at the first place it's used, and then reused the result. If that first use is only executed conditionally (as above), then it breaks - `y.sub(x)` just goes and grabs a result for `x` that was never calculated because the `if` didn't go that way.
This change adds the concept of "execution contexts" to the compiler; each level of branching effectively adds a new context. This allows us to make better decisions about when a result has definitely been calculated or whether we need to do it again.
There are a few TODOs left because we can still …
=> libelement: [LMNT] improvements to conditional execution

libelement/CMakeLists.txt
currently fails when libelement is itself included through add_subdirectory, as LMNT's path will be relative to the root project, not libelement.
=> libelement: fix the add_subdirectory path to LMNT

LMNT/doc/Bytecode.md, LMNT/include/lmnt/archive.h, LMNT/src/validation.c, LMNT/test/CMakeLists.txt, LMNT/test/test_archive.h, LMNT/test/test_interpreter.c, LMNT/test/test_jit_native.c, LMNT/test/testhelpers.h, libelement.CLI/include/evaluate_command.hpp, libelement/src/lmnt/compiler.cpp, libelement/src/lmnt/compiler.hpp, libelement/test/lmnt_test.cpp
This new flag allows consumers of archives to determine whether a given function includes backward-facing branches, and therefore is not guaranteed to halt. The flag is set at archive generation time and must be accurate for the archive to be valid.
LMNT changes:
- Removes defunct def flag `LMNT_DEFFLAG_LAMBDA`
- Adds new def flag `LMNT_DEFFLAG_HAS_BACKBRANCHES`
- Adds validation logic to check the accuracy of the backbranches flag
- Adds validation logic to consider a function invalid if an instruction branches (conditionally or unconditionally) to itself
- Adds tests to check validation behaviour
- Fixes pre-existing incorrect bitwise validation check
libelement changes:
- Adds support for compilation stage setting def flags
- Sets backbranches flag if `for` instruction is compiled
- …
=> LMNT: add backbranches flag to function definitions

LMNT/include/lmnt/config.h, LMNT/src/interpreter.c, LMNT/src/ops_trig.c, libelement.CLI/include/evaluate_command.hpp, libelement/src/lmnt/compiler.cpp
We use `sincosf` where available, but this is shipped under different names by glibc and others (e.g. macOS's BSD-derived libc).
This PR updates our behaviour so that `sincosf` is purely opt-in via a config.h definition, as well as fixing a couple of other build issues.
=> LMNT: fix check for using sincos

LMNT/include/lmnt/config.h, LMNT/include/lmnt/jit.h, LMNT/src/jit/jit-armv7m.dasc, LMNT/src/jit/jit-x86_64.dasc, LMNT/src/jit/jit.c, LMNT/src/validation.c, LMNT/test/testsetup_jit_native.h, LMNT/testapp/main.c, libelement.CLI/include/evaluate_command.hpp
- Changes `lmnt_jit_fn_data` to also contain the pointer to the `lmnt_def` it was compiled from
- Removes `const lmnt_def*` parameters from JIT functions that take an `fn_data` since they're now redundant
- Changes `lmnt_jit_fn_data` to also contain a pointer to code which can be used to interrupt execution, as well as pointers to help determine whether it's safe to do so
- Adds `lmnt_jit_is_interruptible(fndata, void*)` to decide whether it's safe to interrupt a running JIT function
- Changes the "should stack constants be modifiable by LMNT instructions" question to be a config #define
=> LMNT: start of JIT interrupt support, other small adjustments

libelement.CLI/include/evaluate_command.hpp, libelement/src/instruction_tree/instructions.cpp, libelement/src/instruction_tree/instructions.hpp, libelement/src/lmnt/compiler.cpp
- Updates libelement.CLI's LMNT archive packaging to match the updated def structure (we really need to find a way of centralising this logic, we've got at least three copies of this in different projects :joy:)
- Makes libelement.CLI also print out the LMNT constants when evaluating, which makes it easier to mentally track the LMNT stack when executing
- Adds a `get_constant_value` method to `element::instruction`, which determines whether this instruction produces a single compile-time constant result and passes out that value if so (or returns `false` if the expression doesn't match those requirements)
- Changes the libelement LMNT compiler to use `get_constant_value` for its constant detection so it catches more types of constant expressions than just actual constant nodes
- Adds …
=> libelement: LMNT compiler improvements, CLI fixes

LMNT/src/validation.c, LMNT/testapp/circle.h, LMNT/testapp/circle_double.h, LMNT/testapp/circle_ht.h, LMNT/testapp/main.c, libelement/src/lmnt/compiler.cpp
**LMNT**
- Tightens validation of defs to ensure that `stack_count >= args_count + rvals_count`
- Changes testapp examples to use split two-part time (integer + fractional)
- Changes testapp examples to use combined `SINCOS` instruction where appropriate
- Adds function to testapp to print the archive in use as raw hex bytes
**libelement**
- LMNT compiler: add constant-base optimisation for `LN` (base `e`) along with the others recently added
=> LMNT: small tweaks

LMNT/include/lmnt/interpreter.h, LMNT/src/dispatch_computed_goto.h, LMNT/src/dispatch_jumptable.h
- Removes jump table's "special" interrupt mode where it swaps the jump table for an interrupt-only one
- Replaces it with the standard "check the status flags" method of interrupting, which is actually now faster
- Updates computed goto dispatch so it always respects the interrupt flag (costs ~3-4% perf in a quick test)
=> LMNT: small dispatch optimisations

LMNT/CMakeLists.txt, LMNT/src/jit/CMakeLists.txt
The main CMakeLists check should ensure that `NATIVE` is only transformed into the current native architecture _if_ there is a JIT implementation for that architecture; otherwise it's just removed.
The second check inside the JIT CMakeLists should ensure that when building the JIT is enabled and it's trying to build for a particular architecture (native or otherwise), a good error message is generated if that architecture doesn't have a JIT implementation.
=> LMNT: added better CMake checks when choosing which JIT architectures to build

.clang-format, libelement.CLI/include/compile_command.hpp, libelement.CLI/include/declaration_command.hpp, libelement.CLI/include/evaluate_command.hpp, libelement.CLI/include/parse_command.hpp, libelement/CMakeLists.txt, libelement/include/element/ast.h, libelement/include/element/common.h, libelement/include/element/interpreter.h, libelement/include/element/object.h, libelement/include/element/parser.h, libelement/include/element/token.h, libelement/src/interpreter.cpp, libelement/src/lmnt/compiler.cpp, libelement/src/lmnt/compiler.hpp, libelement/src/lmnt/exporter.cpp, libelement/src/object_model/declarations/function_declaration.hpp, libelement/src/object_model/metainfo.cpp, libelement/test/lmnt_test.cpp
- Adds API function to generate an LMNT archive from one or more Element declarations
- Adds exporting of API functions when built as a shared library
- Turns off max empty lines in clang-format
- Turns off a couple of cast options in clang-format since they were misidentifying a variable in brackets as a type/cast
=> libelement: add LMNT export functions

.github/workflows/libelement.CLI.yml, .github/workflows/libelement.yml
Previously we were targeting `windows-latest` and specifying VS2019 as our CMake generator; `windows-latest` has been updated to match `windows-2022` which has VS2022.
This change updates the build to build using VS2022 and pins the image we use for building to be `windows-2022` so this doesn't break when `windows-latest` next updates.
=> Updated Windows CI build target to VS2022 and pin to windows-2022 version
